export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const ADD_TO_QUANTITY = "ADD_TO_QUANTITY";
export const SUBTRACT_FROM_QUANTITY = "SUBTRACT_FROM_QUANTITY";