export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const FILTER_BY_SEARCH = "FILTER_BY_SEARCH";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
